import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";

const ProductSans = localfont({
  src: [
    {
      path: '../public/fonts/Product Sans Regular.ttf',
      weight: '400',
      style: 'normal',
    },
        {
      path: '../public/fonts/Product Sans Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: "--font-product-sans",
});

export const metadata: Metadata = {
  title: "Personalized AI Workspace",
  description: "Generated by ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ProductSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
